Version 1.2.6p12
Multiple updates to latest check_mk raw agent version

diff --git a/osx/check_mk_agent b/osx/check_mk_agent
--- a/osx/check_mk_agent
+++ b/osx/check_mk_agent
@@ -36,6 +36,7 @@ unset LANG
 
 export MK_LIBDIR="/usr/lib/check_mk_agent"
 export MK_CONFDIR="/etc/check_mk"
+export MK_VARDIR="/var/lib/check_mk_agent"
 
 # Provide information about the remote host. That helps when data
 # is being sent only once to each remote host.
@@ -60,7 +61,7 @@ LOCALDIR=$MK_LIBDIR/local
 
 # All files in SPOOLDIR will simply appended to the agent
 # output if they are not outdated (see below)
-SPOOLDIR=$MK_CONFDIR/spool
+SPOOLDIR=$MK_VARDIR/spool
 
 # close standard input (for security reasons) and stderr
 if [ "$1" = -d ]
@@ -81,6 +82,8 @@ function run_cached () {
 
     if [ ! -d $MK_CONFDIR/cache ]; then mkdir -p $MK_CONFDIR/cache ; fi
     CACHEFILE="$MK_CONFDIR/cache/$NAME.cache"
+    if [ ! -d $MK_VARDIR/cache ]; then mkdir -p $MK_VARDIR/cache ; fi
+    CACHEFILE="$MK_VARDIR/cache/$NAME.cache"
 
     # Check if the creation of the cache takes suspiciously long and return
     # nothing if the age (access time) of $CACHEFILE.new is twice the MAXAGE
@@ -88,7 +91,11 @@ function run_cached () {
     if [ -e "$CACHEFILE.new" ] ; then
         local CF_ATIME=$(stat -c %X "$CACHEFILE.new")
         if [ $((NOW - CF_ATIME)) -ge $((MAXAGE * 2)) ] ; then
-            return
+            # Kill the process still accessing that file in case
+            # it is still running. This avoids overlapping processes!
+            fuser -f "$CACHEFILE.new" >/dev/null 2>&1 | xargs -L 1 kill -9
+            rm -f "$CACHEFILE.new"
+			return
         fi
     fi
 
@@ -103,7 +110,8 @@ function run_cached () {
 
     # Cache file outdated and new job not yet running? Start it
     if [ -z "$USE_CACHEFILE" -a ! -e "$CACHEFILE.new" ] ; then
-        echo "set -o noclobber ; exec > \"$CACHEFILE.new\" || exit 1 ; $CMDLINE && mv \"$CACHEFILE.new\" \"$CACHEFILE\" || rm -f \"$CACHEFILE\" \"$CACHEFILE.new\"" | bash 2>/dev/null &
+    	# When the command fails, the output is throws away ignored
+        echo "set -o noclobber ; exec > \"$CACHEFILE.new\" || exit 1 ; $CMDLINE && mv \"$CACHEFILE.new\" \"$CACHEFILE\" || rm -f \"$CACHEFILE\" \"$CACHEFILE.new\"" | nohup bash >/dev/null 2>&1 &
     fi
 }
 
@@ -111,12 +119,13 @@ function run_cached () {
 export -f run_cached
 
 echo '<<<check_mk>>>'
-echo Version: 1.2.5i6a
+echo Version: 1.2.6p12
 echo AgentOS: darwin
+echo AgentDirectory: $MK_CONFDIR
+echo DataDirectory: $MK_VARDIR
+echo SpoolDirectory: $SPOOLDIR
 echo PluginsDirectory: $PLUGINSDIR
 echo LocalDirectory: $LOCALDIR
-echo SpoolDirectory: $SPOOLDIR
-echo AgentDirectory: $MK_CONFDIR
 
 osver="$(uname -r)"
 
@@ -126,38 +135,30 @@ df -kPT hfs | sed -e 's/^\([^ ][^ ]*\) \(.*\)$/\1 hfs \2/' | sed 1d
 # processes including username, without kernel processes
 echo '<<<ps>>>'
 COLUMNS=10000
-ps ax -o user,vsz,rss,pcpu,command | sed -e 1d -e 's/ *\([^ ]*\) *\([^ ]*\) *\([^ ]*\) *\([^ ]*\) */(\1,\2,\3,\4) /' | sed 's/^[ \t]*//;s/[ \t]*$//' | grep -v '(root,0,0,0.0)'
+ps ax -o user,vsz,rss,pcpu,pid,command | sed -e 1d -e 's/ *\([^ ]*\) *\([^ ]*\) *\([^ ]*\) *\([^ ]*\) */(\1,\2,\3,\4) /' | sed 's/^[ \t]*//;s/[ \t]*$//' | grep -v '(root,0,0,0.0)'
 
 # Memory Usage.
-if which vm_stat >/dev/null
-then
-  echo '<<<mem>>>'
-  ## fill array with values from mv_stats command with values:
-  ## ( free active inactive speculative "wired down" "copy-on-write" "zero filled" reactivated ins outs )
-  paging=4096
-  vstats=( $(vm_stat | egrep '^Pages' | sed 's/^.*: *//' | tr -d '.' | tr '\n' ' ') )
-  echo "MemTotal:   $((`sysctl -n hw.memsize` >> 10)) KB"
-  echo "MemFree:    $(( (${vstats[0]} * $paging) >> 10 )) KB"
-  echo "Active:     $(( (${vstats[1]} * $paging) >> 10 )) KB"
-  echo "Inactive:   $(( (${vstats[2]} * $paging) >> 10 )) KB"
-  echo "Mapped:     $(( (${vstats[4]} * $paging) >> 10 )) KB"
-fi
-if which sysctl >/dev/null
-then
-  swapusage=( $(sysctl -n vm.swapusage | tr -cd "[:digit:] .") )
-  echo "SwapTotal:  $(bc -l -q <<< "${swapusage[0]} * 1024" | xargs printf "%1.0f") KB"
-  echo "SwapFree:   $(bc -l -q <<< "${swapusage[2]} * 1024" | xargs printf "%1.0f") KB"
-fi
+echo '<<<mem>>>'
+## fill array with values from mv_stats command with values:
+## ( free active inactive speculative "wired down" "copy-on-write" "zero filled" reactivated ins outs )
+paging=4096
+vstats=( $(vm_stat | egrep '^Pages' | sed 's/^.*: *//' | tr -d '.' | tr '\n' ' ') )
+echo "MemTotal:   $((`sysctl -n hw.memsize` >> 10)) KB"
+echo "MemFree:    $(( (${vstats[0]} * $paging) >> 10 )) KB"
+echo "Active:     $(( (${vstats[1]} * $paging) >> 10 )) KB"
+echo "Inactive:   $(( (${vstats[2]} * $paging) >> 10 )) KB"
+echo "Mapped:     $(( (${vstats[4]} * $paging) >> 10 )) KB"
+
+swapusage=( $(sysctl -n vm.swapusage | tr -cd "[:digit:] .") )
+echo "SwapTotal:  $(bc -l -q <<< "${swapusage[0]} * 1024" | xargs printf "%1.0f") KB"
+echo "SwapFree:   $(bc -l -q <<< "${swapusage[2]} * 1024" | xargs printf "%1.0f") KB"
 
 # CPU Usage.
-if which sysctl >/dev/null
-then
-  echo '<<<cpu>>>'
-  loads=$(sysctl -n vm.loadavg| tr -cd "[:digit:] ." | sed 's/^[ \t]*//;s/[ \t]*$//')
-  procs=$(ps ax -o start,state,pid | sed 1d | awk '$2 ~ /R/{n++} END{printf("%d/%d %d", n, NR, $3)}')
-  cpus=$(sysctl -n hw.ncpu)
-  echo "$loads $procs $cpus"
-fi
+echo '<<<cpu>>>'
+loads=$(sysctl -n vm.loadavg| tr -cd "[:digit:] ." | sed 's/^[ \t]*//;s/[ \t]*$//')
+procs=$(ps ax -o start,state,pid | sed 1d | awk '$2 ~ /R/{n++} END{printf("%d/%d %d", n, NR, $3)}')
+cpus=$(sysctl -n hw.ncpu)
+echo "$loads $procs $cpus"
 
 # Uptime
 # Calculate the uptime in seconds since epoch compatible to /proc/uptime in linux
@@ -166,7 +167,6 @@ echo `date +%s` - `sysctl -n kern.boottime | cut -d' ' -f 4,7 | tr ',' '.' | tr 
 
 # Network interfaces (Link, Autoneg, Speed)
 echo '<<<netif>>>'
-
 ifconfig -au | sed '/^[a-z]/{x;p;x;}' | \
 awk 'BEGIN { RS = "" ; FS = "\n" } \
 !/^[lo|fw]/{ split($1,n,":"); name = n[1]; \
@@ -231,20 +231,53 @@ then
     run_cached -s ipmi 300 "ipmitool sensor list | tail -n +2 | grep -v 'command failed' | sed -e 's/ *| */|/g' -e 's/ /_/g' -e 's/_*"'$'"//' -e 's/|/ /g' | egrep -v '^[^ ]+ na ' | grep -v ' discrete '"
 fi
 
-# Time synchronization with NTP
-if type ntpq > /dev/null 2>&1 ; then
-   # remove heading, make first column space separated
-   run_cached -s ntp 30 "waitmax 5 ntpq -np | sed -e 1,2d -e 's/^\(.\)/\1 /' -e 's/^ /%/'"
+# VirtualBox Guests. Section must always been output. Otherwise the
+# check would not be executed in case no guest additions are installed.
+# And that is something the check wants to detect
+echo '<<<vbox_guest>>>'
+if type VBoxControl >/dev/null 2>&1 ; then
+    VBoxControl -nologo guestproperty enumerate | cut -d, -f1,2
+    [ ${PIPESTATUS[0]} = 0 ] || echo "ERROR"
 fi
 
-# Checks for cups monitoring
-if which lpstat >/dev/null 2>&1; then
-		echo '<<<cups_queues>>>'
-		waitmax 3 lpstat -p
-		echo '---'
-		for i in $(waitmax 3 lpstat -p | grep -E "^(printer|Drucker)" | awk '{print $2}' | grep -v "@"); do
-				waitmax 3 lpstat -o "$i"
-		done
+# Time synchronization with NTP
+# remove heading, make first column space separated
+run_cached -s ntp 30 "waitmax 5 ntpq -np | sed -e 1,2d -e 's/^\(.\)/\1 /' -e 's/^ /%/'"
+
+# Status of CUPS printer queues
+if type lpstat > /dev/null 2>&1; then
+    if pgrep -x cupsd > /dev/null 2>&1; then
+        # first define a function to check cups
+        function cups_queues () {
+            CPRINTCONF=/etc/cups/printers.conf
+            if [ -r "$CPRINTCONF" ] ; then
+                LOCAL_PRINTERS=$(grep -E "<(Default)?Printer .*>" $CPRINTCONF | awk '{print $2}' | sed -e 's/>//')
+                lpstat -p | while read LINE
+                do
+                    PRINTER=$(echo $LINE | awk '{print $2}')
+                    if echo "$LOCAL_PRINTERS" | grep -q "$PRINTER"; then
+                        echo $LINE
+                    fi
+                done
+                echo '---'
+                lpstat -o | while read LINE
+                do
+                    PRINTER=${LINE%%-*}
+                    if echo $LOCAL_PRINTERS | grep -q $PRINTER; then
+                        echo $LINE
+                    fi
+                done
+            else
+                lpstat -p
+                echo '---'
+                lpstat -o | sort
+            fi
+        }
+        # Make cups_queues available for subshell
+        export -f cups_queues
+        # Use cups_queues function with run_cached and cache time of 5 mins
+        run_cached -s cups_queues 300 "cups_queues"
+    fi
 fi
 
 # Heartbeat monitoring
@@ -284,16 +317,38 @@ fi
 # Only handle the last 6 lines (includes the summary line at the bottom and
 # the last message in the queue. The last message is not used at the moment
 # but it could be used to get the timestamp of the last message.
-if type mailq >/dev/null 2>&1 && [ -x /usr/sbin/postfix ] && getent passwd postfix >/dev/null 2>&1; then
-	echo '<<<postfix_mailq>>>'
-	mailq | tail -n 6
+# we determine the number of mails and their size in several postfix mail queues
+if type postconf >/dev/null ; then
+    echo '<<<postfix_mailq>>>'
+    postfix_queue_dir=$(postconf -h queue_directory)
+    postfix_count=$(find $postfix_queue_dir/deferred -type f | wc -l)
+    postfix_size=$(du -ks $postfix_queue_dir/deferred | awk '{print $1 }')
+    if [ $postfix_count -gt 0 ]
+    then
+       echo -- $postfix_size Kbytes in $postfix_count Requests.
+    else
+       echo Mail queue is empty
+    fi
 fi
 
 # Fileinfo-Check: put patterns for files into /etc/check_mk/fileinfo.cfg
 if [ -r "$MK_CONFDIR/fileinfo.cfg" ] ; then
     echo '<<<fileinfo:sep(124)>>>'
     date +%s
-    stat -f "%N|%z|%m" $(cat "$MK_CONFDIR/fileinfo.cfg")
+    for line in $(cat "$MK_CONFDIR/fileinfo.cfg")
+    do
+        stat -f "%N|%z|%m" $line 2>/dev/null
+
+        if [ $? -ne 0 ]; then
+            echo "$line|missing|$(date +%s)"
+        fi
+    done
+fi
+
+if type tmutil >/dev/null
+then
+    echo '<<<timemachine>>>'
+    tmutil latestbackup 2>&1
 fi
 
 # Local checks
